# Generated by Django 4.1 on 2023-03-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0006_date2_delete_date1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='date2',
            new_name='date1',
        ),
    ]
