# Generated by Django 4.1 on 2023-03-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_datetime1_delete_date1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datetime1',
            table='datetime1',
        ),
    ]
