# Generated by Django 4.1 on 2023-02-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_faculty_student_delete_mms'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PFSDTeamName', models.CharField(max_length=100)),
                ('CLUSTER', models.IntegerField(max_length=2)),
                ('TEAM', models.IntegerField(max_length=2)),
                ('StudentID', models.IntegerField(max_length=20)),
                ('TeamLead', models.CharField(max_length=20)),
                ('BusinessSystem', models.CharField(max_length=100)),
                ('FacultyMentor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teamdetails',
            },
        ),
    ]
