# Generated by Django 4.1 on 2023-03-01 04:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_teamdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('firstname', models.TextField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('comments', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.AlterModelManagers(
            name='faculty',
            managers=[
                ('fac', django.db.models.manager.Manager()),
            ],
        ),
    ]
