# Generated by Django 4.1.7 on 2023-03-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_alter_datetime1_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='faculty',
            managers=[
            ],
        ),
    ]
